<?php

namespace Ludelix\Core\Console\Commands;

use Ludelix\Interface\Console\CommandInterface;
use Ludelix\Core\Support\Str;

/**
 * MakeEntityCommand - Generate Entity Classes
 * 
 * CLI command to generate ORM entity classes
 */
class MakeEntityCommand implements CommandInterface
{
    public function getName(): string
    {
        return 'make:entity';
    }

    public function getDescription(): string
    {
        return 'Create a new ORM entity class';
    }

    public function getArguments(): array
    {
        return [
            'name' => 'The name of the entity class'
        ];
    }

    public function getOptions(): array
    {
        return [
            '--table' => 'Specify the database table name',
            '--repository' => 'Generate a custom repository class',
            '--tenant' => 'Make the entity tenant-scoped',
            '--force' => 'Overwrite existing files'
        ];
    }

    public function execute(array $arguments, array $options): int
    {
        $name = $arguments['name'] ?? null;
        
        if (!$name) {
            echo "Error: Entity name is required\n";
            return 1;
        }

        $className = Str::studly($name);
        $tableName = $options['table'] ?? Str::snake(Str::plural($name));
        $withRepository = isset($options['repository']);
        $isTenantScoped = isset($options['tenant']);
        $force = isset($options['force']);

        // Generate entity file
        $entityPath = $this->generateEntity($className, $tableName, $isTenantScoped, $force);
        
        if ($entityPath) {
            echo "Entity created: {$entityPath}\n";
        }

        // Generate repository if requested
        if ($withRepository) {
            $repositoryPath = $this->generateRepository($className, $force);
            if ($repositoryPath) {
                echo "Repository created: {$repositoryPath}\n";
            }
        }

        return 0;
    }

    protected function generateEntity(string $className, string $tableName, bool $isTenantScoped, bool $force): ?string
    {
        $path = app_path("Entities/{$className}.php");
        
        if (file_exists($path) && !$force) {
            echo "Error: Entity {$className} already exists. Use --force to overwrite.\n";
            return null;
        }

        $tenantAttributes = $isTenantScoped ? "\n#[TenantScoped(tenantColumn: 'tenant_id')]" : '';
        $tenantProperty = $isTenantScoped ? "\n    #[Column(type: 'int', nullable: true)]\n    public ?int \$tenantId = null;\n" : '';

        $content = "<?php

namespace App\\Entities;

use Ludelix\\ORM\\Attributes\\Entity;
use Ludelix\\ORM\\Attributes\\Column;
use Ludelix\\ORM\\Attributes\\PrimaryKey;
use Ludelix\\ORM\\Attributes\\LifecycleCallbacks;" . ($isTenantScoped ? "\nuse Ludelix\\ORM\\Attributes\\TenantScoped;" : '') . "

/**
 * {$className} Entity
 * 
 * Generated by Ludelix ORM
 */
#[Entity(table: '{$tableName}')]
#[LifecycleCallbacks(['prePersist'])]{$tenantAttributes}
class {$className}
{
    #[PrimaryKey(autoIncrement: true)]
    #[Column(type: 'int')]
    public int \$id;

    #[Column(type: 'datetime')]
    public \\DateTime \$createdAt;

    #[Column(type: 'datetime')]
    public \\DateTime \$updatedAt;{$tenantProperty}

    public function __construct()
    {
        \$this->createdAt = new \\DateTime();
        \$this->updatedAt = new \\DateTime();
    }

    /**
     * Pre-persist lifecycle callback
     */
    public function prePersist(): void
    {
        \$this->updatedAt = new \\DateTime();
        
        if (!\$this->createdAt) {
            \$this->createdAt = new \\DateTime();
        }
    }
}";

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        file_put_contents($path, $content);
        return $path;
    }

    protected function generateRepository(string $className, bool $force): ?string
    {
        $path = app_path("Repositories/{$className}Repository.php");
        
        if (file_exists($path) && !$force) {
            echo "Error: Repository {$className}Repository already exists. Use --force to overwrite.\n";
            return null;
        }

        $content = "<?php

namespace App\\Repositories;

use App\\Entities\\{$className};
use Ludelix\\ORM\\Repository\\Repository;

/**
 * {$className}Repository - Custom {$className} Repository
 * 
 * Generated by Ludelix ORM
 */
class {$className}Repository extends Repository
{
    /**
     * Find active records
     */
    public function findActive(): array
    {
        return \$this->createQueryBuilder('e')
            ->where('active', '=', true)
            ->orderBy('createdAt', 'DESC')
            ->get();
    }

    /**
     * Find by date range
     */
    public function findByDateRange(\\DateTime \$start, \\DateTime \$end): array
    {
        return \$this->createQueryBuilder('e')
            ->where('createdAt', '>=', \$start->format('Y-m-d H:i:s'))
            ->where('createdAt', '<=', \$end->format('Y-m-d H:i:s'))
            ->orderBy('createdAt', 'DESC')
            ->get();
    }
}";

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        file_put_contents($path, $content);
        return $path;
    }
}